POST  http://localhost:5000/rooms/join/202020115
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsic3R1ZGlkX2ZsZCI6IjIwMjAyMDExNSIsInJlY25vX3VpZCI6MTcyLCJlbWFpbF9mbGQiOiIyMDIwMjAxMTVAZ29yZG9uY29sbGVnZS5lZHUucGgiLCJwYXNzd29yZF9mbGQiOiIkMmIkMTAkNWZrRW1tMlh2N1BVVVc0MVMxUXdQTzVWaWNjb3NvbFV0bVJqWUdORTQxc0xpVGQwSnNsVC4iLCJyb2xlX2ZsZCI6InVzZXIiLCJsYXN0X2xvZ2luX1RTX2ZsZCI6IjIwMjItMDItMTZUMDI6Mjg6NTkuMDAwWiIsImRhdGVfY3JlYXRlZF9UU19mbGQiOiIyMDIxLTExLTA4VDE3OjQyOjIwLjAwMFoiLCJ1cGRhdGVkX0F0X2ZsZCI6bnVsbCwiZGVsZXRlZF9BdF9mbGQiOm51bGwsImlzX2RlbGV0ZWRfZmxkIjowLCJmbmFtZV9mbGQiOiJNYWUiLCJtbmFtZV9mbGQiOm51bGwsImxuYW1lX2ZsZCI6IldhbGtlciIsImV4dG5hbWVfZmxkIjpudWxsLCJkZXB0X2ZsZCI6IkNDUyIsInByb2dyYW1fZmxkIjoiQlNJVCIsImF2YXRhcl9mbGQiOiIxNjQ0NzY3Nzc2NjU5In0sImlhdCI6MTY0NjUyNTE4MSwiZXhwIjoxNjQ2NjExNTgxfQ.TZSp8--_XK1EzzA5OFyA_IVXdfvRUi5V_NmhDlLKjjk

# {
#     "rname_fld" : "TESTING",
#     "objective_fld": "testing",
#     "requested_by_fld" : "Mae Walker"
# }